services:
  - type: web
    name: islamic-podcast-bot
    env: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/bassetred10/bot-podcast-islamic
    plan: free
    port: 8000
    healthCheckPath: /health
    healthCheckTimeout: 100
    restartPolicy: always
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: BOT_TOKEN
        sync: false
        required: true
      - key: CHANNEL_ID
        value: -1004304853750
      - key: CHANNEL_USERNAME
        value: uec_u
      - key: ADMIN_ID
        value: 6046274404
      - key: COOKIES_FILE
        value: cookies.txt
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
      - key: ENABLE_RATE_LIMIT
        value: "true"
      - key: MAX_REQUESTS_PER_MINUTE
        value: "30"
      - key: ENABLE_ANTI_SPAM
        value: "true"
