services:
  - type: worker
    name: islamic-podcast-bot
    env: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/bassetred10/bot-podcast-islamic
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        value: -1004304853750
      - key: CHANNEL_USERNAME
        value: uec_u
      - key: ADMIN_ID
        value: 6046274404
      - key: COOKIES_FILE
        value: cookies.txt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
